# Generated by Django 3.2.6 on 2021-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
