from .views import *
from .user_views import *
from .role_views import *
from .area_view import *
from .camera_view import *
from .violation_view import *
from .violationType_view import *
from .object_class_views import *
from .image_view import *
